### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by leecig** [238SAMIxD/discord-ai-bot#3]
npm start

> start
> node src/index.js

/home/user/ollama_discord_bot/node_modules/discord.js/src/client/BaseClient.js:29
        userAgentAppendix: options.rest?.userAgentAppendix
                                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lee/ollama_discord_bot/node_modules/discord.js/src/index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by sophuric** [comment]
What version of discord.js are you on? You can run `npm list`

**Comment by MostlyKIGuess** [comment]
> What version of discord.js are you on? You can run `npm list`

same error, I am on 14.14.1

it's still not working

**Comment by MostlyKIGuess** [comment]
oooO here's the fix:

I think the line which was displaying the error was due to the fact it needs node version greater than 14.0.0 

here's how you can install the recent most stable version:

Using n:

Install n using npm (Node.js package manager):

-  bash:
```
npm install -g n
Use n to install a specific Node.js version:
```

- bash:
```
n 20.0.9
```
- Verify the Node.js version:

bash
```
node -v
```

**Comment by sophuric** [comment]
I think this is a bug in Discord.js instead of my code

**Comment by MostlyKIGuess** [comment]
> I think this is a bug in Discord.js instead of my code

it's not a bug in your code, it's just that the syntax in js follow node v 14 and above, and I think updating it should just work fine

**Comment by sophuric** [comment]
do I just put a disclaimer in the README to update to the latest Node version?

**Comment by MostlyKIGuess** [comment]
> do I just put a disclaimer in the README to update to the latest Node version?

Yeah cool , 
Error : 
The ?. operator was introduced in ECMAScript 2020 (ES11) and requires a Node.js version of 14.0.0 or later.


So just add that you need node - v atleast greater than 14..

**Comment by sophuric** [comment]
Done! 75d8828dafb33db47730f4f75c1241b18925238f
